External dns certificate automation
equinor/radix-operator pull request #1016
Opened 2023-12-19 11:35 UTC by nilsgstrabo

2023-12-20 13:16 UTC, satr requested changes
Suggested changes

2023-12-20 13:16 UTC, satr commented on pkg/apis/deployment/secrets.go
> +			if externalAlias.UseCertificateAutomation {
Because "Cert manager will create the TLS secret", should we try to delete existing secret `externalAlias.FQDN` before `continue`?

2023-12-20 13:16 UTC, satr commented on radix-operator/deployment/handler.go
> +	// tenantId                string
Outdated code?

2023-12-20 13:27 UTC, nilsgstrabo commented on pkg/apis/deployment/deployment_test.go
> +				WithExternalDNS(radixv1.RadixDeployExternalDNS{FQDN: "some.alias.com"}, radixv1.RadixDeployExternalDNS{FQDN: "another.alias.com"}).
fixed

2023-12-20 13:32 UTC, nilsgstrabo commented on pkg/apis/deployment/deployment_test.go
> +	_, _ = radixclient.RadixV1().RadixRegistrations().Create(context.Background(), rr, metav1.CreateOptions{})
fixed

2023-12-20 13:44 UTC, nilsgstrabo commented on pkg/apis/deployment/ingress.go
> +						if err := deleteTLSSecretForIngress(existingIngress, deploy.kubeclient); err != nil {
fixed

2023-12-20 13:45 UTC, nilsgstrabo commented on pkg/apis/deployment/ingress.go
> +						if err := clearTLSSecretDataForIngress(existingIngress, deploy.kubeclient); err != nil {
fixed

2023-12-20 13:45 UTC, nilsgstrabo commented on pkg/apis/deployment/ingress.go
> +				if err := deleteTLSSecretForIngress(ingress, deploy.kubeclient); err != nil {
fixed

2023-12-20 13:59 UTC, nilsgstrabo commented on pkg/apis/deployment/secrets.go
> +			if externalAlias.UseCertificateAutomation {
The secret is deleted by createOrUpdateExternalDNSIngresses when the external alias "switches" from manual to automation.

2023-12-20 13:59 UTC, nilsgstrabo commented on radix-operator/deployment/handler.go
> +	// tenantId                string
removed

2023-12-20 14:08 UTC, nilsgstrabo commented on pkg/apis/deployment/secrets.go
> +			if externalAlias.UseCertificateAutomation {
Added comment in code to explain

2023-12-20 14:19 UTC, nilsgstrabo commented on pkg/apis/deployment/ingress.go
> +	if len(externalDNSList) > 0 && isActiveCluster(clustername) {
fixed

2023-12-20 14:22 UTC, nilsgstrabo commented on pkg/apis/deployment/ingress.go
> +				if useCertificateAutomationForExternalDNS(ingress) != useCertificateAutomationForExternalDNS(existingIngress) {
fixed

2023-12-20 15:06 UTC, satr approved these changes

2023-12-22 12:47 UTC, Richard87 approved these changes
lgtm

2023-12-29 12:29 UTC, Richard87 submitted a review, later dismissed
godkjent

2024-01-11 12:30 UTC, Richard87 approved these changes
godkjent

2024-01-16 08:15 UTC, merged