Deploy only specific component
equinor/radix-operator pull request #1038
Opened 2024-01-16 14:51 UTC by satr

2024-01-18 12:28 UTC, nilsgstrabo requested changes
The functionality seems ok, but there are no unit tests for the deploy step to verify that when a list of components is specified, they are actually preserved from current active deployment.

2024-01-19 12:17 UTC, satr commented on pipeline-runner/steps/deploy.go
> +func (cli *DeployStepImplementation) validate(pipelineInfo *model.PipelineInfo, env string) error {
Moved

2024-01-19 15:00 UTC, nilsgstrabo commented on pipeline-runner/steps/deploy.go
> +	activeRadixDeployment, err := cli.GetKubeutil().GetActiveDeployment(utils.GetEnvironmentNamespace(appName, env))
Use existing function getCurrentRadixDeployment. This function ignores Forbidden errors in cases where a new environment is added to radixconfig, or radixconfig is applied for the first time, and the RA controller has not yet finished reconciling RBAC

2024-01-19 16:07 UTC, satr commented on pipeline-runner/steps/deploy.go
> +	activeRadixDeployment, err := cli.GetKubeutil().GetActiveDeployment(utils.GetEnvironmentNamespace(appName, env))
Fixed

2024-01-22 07:41 UTC, nilsgstrabo approved these changes

2024-01-22 07:42 UTC, merged