1120 read only file system
equinor/radix-operator pull request #1049
Opened 2024-02-07 06:47 UTC by nilsgstrabo

2024-02-09 07:39 UTC, anneliawa commented on pkg/apis/radixvalidators/validate_ra.go
> +		/*err = validateUseReadOnlyFileSystem(component.UseReadOnlyFileSystem)
remove?

2024-02-16 13:47 UTC, Richard87 requested changes
Added some test coments

2024-02-19 08:27 UTC, Richard87 submitted a review, later dismissed
Godkjent

2024-02-23 09:11 UTC, Richard87 approved these changes
Godkjent! :D

2024-02-23 09:25 UTC, merged