Use read only fs for Ouath and Job API component
equinor/radix-operator pull request #1095
Opened 2024-04-22 09:04 UTC by Richard87

2024-04-29 10:16 UTC, nilsgstrabo commented on pkg/apis/kube/config_maps.go
> +	_ "github.com/equinor/radix-operator/pkg/apis/test/initlogger"
```suggestion
```
This is not a `test` file, so the logger should not be imported

2024-04-30 07:30 UTC, nilsgstrabo requested changes
Added a few suggestions. Also, the chart and app version should be updated.

2024-04-30 07:30 UTC, nilsgstrabo commented on pkg/apis/utils/resources/resources.go
> +	resourcev1 "k8s.io/apimachinery/pkg/api/resource"
```suggestion
	"k8s.io/apimachinery/pkg/api/resource"
```
resource is not versioned

2024-04-30 07:30 UTC, nilsgstrabo commented on pkg/apis/utils/resources/resources.go
> +func WithCPU(cpu string) ResourceOption {
Consider using type resource.Quantity instead of string. Then you don't need to parse it

2024-04-30 08:09 UTC, Richard87 commented on pkg/apis/test/utils.go
> +}
fixed

2024-04-30 08:28 UTC, Richard87 commented on pkg/apis/utils/resources/resources.go
> +func WithCPU(cpu string) ResourceOption {
fixed

2024-04-30 08:36 UTC, Richard87 commented on pkg/apis/utils/resources/resources.go
> +	resourcev1 "k8s.io/apimachinery/pkg/api/resource"
fixed

2024-04-30 10:35 UTC, merged