Keda Feature
equinor/radix-operator pull request #1112
Opened 2024-05-08 11:36 UTC by Richard87

2024-05-24 06:58 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	CooldownPeriod *int32 `json:"cooldownPeriod"` // 300
Should these have a `// +optional` comment?

2024-05-24 06:59 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	Triggers *[]RadixHorizontalScalingTrigger `json:"triggers,omitempty"`
```suggestion
	Triggers []RadixHorizontalScalingTrigger `json:"triggers,omitempty"`
```
No need to use array pointer

2024-05-24 07:35 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	// Defines the type of metric to use. Options are Utilization or AverageValue. Defaults to Utilization.
According to docs (https://keda.sh/docs/2.14/concepts/scaling-deployments/) the default is AverageValue, not Utilization

2024-05-24 07:37 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	// Defines the type of metric to use. Options are Utilization or AverageValue. Defaults to Utilization.
Default value is AverageValue, not Utilization

2024-05-24 07:39 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	MetricType autoscalingv2.MetricTargetType `json:"metricType,omitempty"`
Consider defining allowed values with +kubebuilder:validation:Enum (https://book.kubebuilder.io/reference/markers/crd-validation) to prevent users from adding invalid values. The validation:Enum also helps autocomplete in editors

2024-05-24 07:39 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	MetricType autoscalingv2.MetricTargetType `json:"metricType,omitempty"` // TODO: Copy values and only allow Utilization and AverageValue
Consider defining allowed values with +kubebuilder:validation:Enum (https://book.kubebuilder.io/reference/markers/crd-validation) to prevent users from adding invalid values. The validation:Enum also helps autocomplete in editors

2024-05-24 07:41 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	AzureServiceBus *RadixHorizontalScalingAzureServiceBusTrigger `json:"azureServiceBus,omitempty"`
Add a short description (as comment) of each property. This will be shown to users in code editors

2024-05-24 07:46 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	Value int `json:"value"`
Can this value be 0 or negative? If not, add marker `+kubebuilder:validation:ExclusiveMinimum` or `+kubebuilder:validation:Minimum` to prevent invalid values (https://book.kubebuilder.io/reference/markers/crd-validation)

2024-05-24 07:46 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	Value int `json:"value"`
Can this value be 0 or negative? If not, add marker `+kubebuilder:validation:ExclusiveMinimum` or `+kubebuilder:validation:Minimum` to prevent invalid values (https://book.kubebuilder.io/reference/markers/crd-validation)

2024-05-24 07:47 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	PollingInterval *int32 `json:"pollingInterval"` // 30
Define minimum allowed values using marker comments (https://book.kubebuilder.io/reference/markers/crd-validation)

2024-05-24 07:47 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	CooldownPeriod *int32 `json:"cooldownPeriod"` // 300
Define minimum allowed values using marker comments (https://book.kubebuilder.io/reference/markers/crd-validation)

2024-05-24 07:49 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	DesiredReplicas int `json:"desiredReplicas"`
Define minimum allowed value using marker comments (https://book.kubebuilder.io/reference/markers/crd-validation)

2024-05-24 07:58 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	End string `json:"end"`
Add a bit more info about what cron format is supported. KEDA docs (https://keda.sh/docs/2.14/scalers/cron/) mentions the Linux cron format (https://en.wikipedia.org/wiki/Cron).

2024-05-24 07:59 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	End string `json:"end"`
If you are good at regexp, perhaps try to define one for the cron and add the `+kubebuilder:validation:Pattern` marker

2024-05-24 08:01 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	// CooldownPeriod to wait after the last trigger reported active before scaling the resource back to 0. Defaults to 5min
Add a linebreak above :)

2024-05-24 08:02 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	AzureServiceBus *RadixHorizontalScalingAzureServiceBusTrigger `json:"azureServiceBus,omitempty"`
Add a linebreak between each prop

2024-05-24 08:04 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	Namespace string `json:"namespace"`
Namespace is only required when using pod identity (possibly also workload identity). Make it optional (add omitempty), and add validation in radixvalidators

2024-05-24 08:06 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	MessageCount *int `json:"messageCount,omitempty"`
Add kubebuilder marker for minimum value

2024-05-24 08:08 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	SubscriptionName *string `json:"subscriptionName,omitempty"`
Is there a max length for these props, and/or a regex pattern?

2024-05-24 08:09 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	// SubscriptionName is required when TopicName is set.
A lineshift above please :)

2024-05-24 08:12 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixapptypes.go
> +type RequiredIdentity struct {
This type is only used by triggers in the radixhorizontalscalingtypes. Should we move it there? Possible give it a name that so we know it has something to do with triggers?

2024-05-24 08:20 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/errors.go
> +	ErrValidationNotImplemented                                            = errors.New("validation not implemented")
This error is not used anywhere. Should we remove it?

2024-05-24 08:23 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	Name            string                                        `json:"name"`
Could you try to see if `+listType` and `+listMapKey` (https://book.kubebuilder.io/reference/markers/crd-processing) can be used to define `name` as a key for the list?

2024-05-24 08:25 UTC, nilsgstrabo commented on pkg/apis/utils/deploymentcomponent_builder.go
> +type HorizontalScalingBuilder interface {
This interface is not used. Should we delete it?

2024-05-24 12:39 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	SubscriptionName *string `json:"subscriptionName,omitempty"`
Hmm, we could,

I made it a pointer to signal that it is optional, but there might be a better way to do it?

2024-05-27 06:11 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	CooldownPeriod *int32 `json:"cooldownPeriod"` // 300
I added 15sec as minimum value for cooldown and polling interval, and thinking we can tweak it in the future if some users have special needs 🤔

2024-05-27 06:33 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	Triggers *[]RadixHorizontalScalingTrigger `json:"triggers,omitempty"`
Fixed

2024-05-27 07:23 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	// Defines the type of metric to use. Options are Utilization or AverageValue. Defaults to Utilization.
Fixed

2024-05-27 07:23 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	// Defines the type of metric to use. Options are Utilization or AverageValue. Defaults to Utilization.
Fixed

2024-05-27 07:24 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra_test.go
> +			[]error{radixvalidators.ErrDuplicateTriggerName},
Perhaps we should add some tests for valid and invalid configurations for Cron and AzureServiceBus, either in this test funtions, or as separate functions. Perhaps having separate functions (one for Cron and one for AzureServiceBus) makes the test cvases morte readable and customizable for each test scenario.

2024-05-27 08:06 UTC, nilsgstrabo commented on pkg/apis/deployment/scaledobject.go
>  			Advanced:        &kedav1.AdvancedConfig{RestoreToOriginalReplicaCount: true},
Missed a bug in the initial PR for scaledobject in line 124. APIVersion should be `apps/v1`, not `apps/radixv1`. Luckily it works with apps/radixv1, so we do not have to make a separate PR to patch it, we can just fix it in this PR.

2024-05-27 08:10 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra.go
> +			if trigger.AzureServiceBus.Namespace == "" {
Namespace is only required when using workload identity (which is the opnly auth we support for the moment). If we add support for connectString authentication, we must ensure that Namespace is no longer required.

2024-05-27 08:11 UTC, nilsgstrabo commented on pkg/apis/deployment/scaledobject.go
> +			}
namespace is only required when using WI auth. Should we ignore the metadata prop for it if it is not set?

2024-05-27 08:13 UTC, nilsgstrabo commented on pkg/apis/deployment/scaledobject.go
> +			if trigger.AzureServiceBus.MessageCount != nil {
We have validation that both must be set. We should therefore trust validation and set each metadata field in the value is set in RadixHorizontalScaling. Split this out in two if blocks

2024-05-27 08:23 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	// SubscriptionName is required when TopicName is set.
Fixed

2024-05-27 08:30 UTC, nilsgstrabo requested changes
Added suggestions

2024-05-27 10:39 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	// SubscriptionName is required when TopicName is set.
fixed

2024-05-27 12:02 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	PollingInterval *int32 `json:"pollingInterval"` // 30
fixed

2024-05-27 12:03 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	// CooldownPeriod to wait after the last trigger reported active before scaling the resource back to 0. Defaults to 5min
fixed

2024-05-27 12:07 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	MetricType autoscalingv2.MetricTargetType `json:"metricType,omitempty"`
Fixed

2024-05-27 12:07 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	Name            string                                        `json:"name"`
fixed

2024-05-27 12:13 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	AzureServiceBus *RadixHorizontalScalingAzureServiceBusTrigger `json:"azureServiceBus,omitempty"`
Fixed

2024-05-27 12:13 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	MetricType autoscalingv2.MetricTargetType `json:"metricType,omitempty"`
fixed

2024-05-27 12:14 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	Value int `json:"value"`
I set it to minimum 15%

2024-05-27 12:14 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	Value int `json:"value"`
Fixed, set to minimum 15%

2024-05-27 12:15 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	End string `json:"end"`
Fixed (needs some testing)

2024-05-27 12:16 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	Namespace string `json:"namespace"`
I'll upgrade it to optional in the next PR

2024-05-27 12:16 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	MessageCount *int `json:"messageCount,omitempty"`
fixed, set to min 1 message

2024-05-27 12:23 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	SubscriptionName *string `json:"subscriptionName,omitempty"`
Fixed,
```	
// +kubebuilder:validation:MinLength=6
// +kubebuilder:validation:MaxLength=50
// +kubebuilder:validation:Pattern=^(([a-z][-a-z0-9]*)?[a-z0-9])?$
```

Namespace requirements:
```
// The namespace can contain only letters, numbers, and hyphens. The namespace must start with a letter, and it must end with a letter or number.
// The value must be between 6 and 50 characters long.
```

2024-05-27 12:33 UTC, Richard87 commented on pkg/apis/radix/v1/radixhorizontalscalingtypes.go
> +	SubscriptionName *string `json:"subscriptionName,omitempty"`
Fant en fin liste over alle requirements https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules

2024-05-28 07:51 UTC, Richard87 commented on pkg/apis/radixvalidators/errors.go
> +	ErrValidationNotImplemented                                            = errors.New("validation not implemented")
Fixed, renamed to RadixHorizontalScalingRequiredIdentity and moved to radixhorizontalscalingtypes.go

2024-05-28 07:51 UTC, Richard87 commented on pkg/apis/radix/v1/radixapptypes.go
> +type RequiredIdentity struct {
Fixed, renamed to RadixHorizontalScalingRequiredIdentity and moved to radixhorizontalscalingtypes.go

2024-05-28 07:52 UTC, Richard87 commented on pkg/apis/radixvalidators/errors.go
> +	ErrValidationNotImplemented                                            = errors.New("validation not implemented")
Fixed

2024-05-28 07:53 UTC, Richard87 commented on pkg/apis/utils/deploymentcomponent_builder.go
> +type HorizontalScalingBuilder interface {
Removed

2024-05-28 08:03 UTC, Richard87 commented on pkg/apis/radixvalidators/validate_ra_test.go
> +			[]error{radixvalidators.ErrDuplicateTriggerName},
We have basic tests around `pkg/apis/radixvalidators/validate_ra_test.go:1743`...

2024-05-28 08:18 UTC, Richard87 commented on pkg/apis/deployment/scaledobject.go
>  			Advanced:        &kedav1.AdvancedConfig{RestoreToOriginalReplicaCount: true},
Thanks, fixed

2024-05-28 08:20 UTC, Richard87 commented on pkg/apis/radixvalidators/validate_ra.go
> +			if trigger.AzureServiceBus.Namespace == "" {
Added todo in code

2024-05-28 08:22 UTC, Richard87 commented on pkg/apis/deployment/scaledobject.go
> +			}
Fixed

2024-05-28 08:26 UTC, Richard87 commented on pkg/apis/deployment/scaledobject.go
> +			if trigger.AzureServiceBus.MessageCount != nil {
Nice, done

2024-05-29 13:51 UTC, nilsgstrabo commented on pkg/apis/deployment/radixcomponent.go
> +	if len(environmentHorizontalScaling.Triggers) > 0 || environmentHorizontalScaling.RadixHorizontalScalingResources != nil {
```suggestion
	if len(environmentHorizontalScaling.Triggers) > 0 || environmentHorizontalScaling.RadixHorizontalScalingResources != nil { //nolint:staticcheck // backward compatibility support
```
Ignore lint warning

2024-05-29 13:52 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra.go
> +	if config.RadixHorizontalScalingResources != nil && len(config.Triggers) > 0 {
```suggestion
	if config.RadixHorizontalScalingResources != nil && len(config.Triggers) > 0 { //nolint:staticcheck // backward compatibility support
```
ignore lint warning

2024-05-30 06:57 UTC, Richard87 commented on pkg/apis/deployment/radixcomponent.go
> +	if len(environmentHorizontalScaling.Triggers) > 0 || environmentHorizontalScaling.RadixHorizontalScalingResources != nil {
fixed

2024-05-30 06:57 UTC, Richard87 commented on pkg/apis/radixvalidators/validate_ra.go
> +	if config.RadixHorizontalScalingResources != nil && len(config.Triggers) > 0 {
fixed

2024-05-30 06:57 UTC, Richard87 commented on pkg/apis/deployment/scaledobject.go
> +		currentAuths, err := deploy.kubeutil.ListTriggerAuthenticationsWithSelector(ctx, namespace, labels.ForComponentName(component.Name).String())
fixed

2024-05-30 11:35 UTC, nilsgstrabo approved these changes

2024-05-30 11:36 UTC, merged