Create scaling objects instead of hpa
equinor/radix-operator pull request #1116
Opened 2024-05-10 08:04 UTC by Richard87

2024-05-15 09:30 UTC, nilsgstrabo requested changes
Added some suggestions and comments.
We must also add ScaledObject to the radix-operator clusterrole (all verbs), and to the radix-api and radix-app-admin-envs clusterroles (get, list, watch) if radix-api needs to read the ScaledObject.

2024-05-15 09:30 UTC, nilsgstrabo commented on pkg/apis/deployment/scaledobject.go
> +func (deploy *Deployment) garbageCollectDeprecatedHPAs(ctx context.Context) error {
This function will delete all HPAs, also HPAs controlled by ScaledObjects. We should only delete HPAs not controlled by ScaledObjects. We can do that by filtering on labels (set by ScaledOBject).
Example of HPA labels:
labels:
    app.kubernetes.io/managed-by: keda-operator
    app.kubernetes.io/name: keda-hpa-server
    app.kubernetes.io/part-of: server
    app.kubernetes.io/version: 2.14.0
    radix-app: radix-api
    radix-component: server
    scaledobject.keda.sh/name: server

2024-05-15 11:54 UTC, Richard87 commented on pkg/apis/utils/scaler.go
> +func GetScaleTrigger(hpa *v1alpha1.ScaledObject, triggerName, triggerType string) *v1alpha1.ScaleTriggers {
Fixed

2024-05-15 11:56 UTC, Richard87 commented on pkg/apis/radixvalidators/validate_ra_test.go
> +			[]error{radixvalidators.ErrMinReplicasGreaterThanMaxReplicas, radixvalidators.ErrMinReplicasGreaterThanMaxReplicas},
Fixed, was a bug :)

2024-05-15 11:58 UTC, Richard87 commented on pkg/apis/radixvalidators/validate_ra_test.go
> +			[]error{},
Nice! Fixed :)

2024-05-15 12:00 UTC, Richard87 commented on pkg/apis/radixvalidators/validate_ra_test.go
>  	}{
Agreed, with `isErrors = nil`, its pretty clear... fixed!

2024-05-15 12:01 UTC, Richard87 commented on pkg/apis/deployment/kubedeployment.go
> +func (deploy *Deployment) recconcileDeployment(ctx context.Context, deployComponent v1.RadixCommonDeployComponent) error {
fixed

2024-05-15 13:16 UTC, Richard87 commented on pkg/apis/deployment/scaledobject.go
> +func (deploy *Deployment) garbageCollectDeprecatedHPAs(ctx context.Context) error {
Fixed: Ignorerer HPA'en hvis `owner` ikke er `RadixDeployment`, da får vi slettet alle gamle hpas, men ikke de nye:

```golang
// If owner reference is *not* RadixDeployment, skip deleting it
if len(hpa.OwnerReferences) == 0 {
	continue
}
if owner := hpa.OwnerReferences[0]; owner.Kind != radixv1.KindRadixDeployment {
	continue
}
```

2024-05-16 06:34 UTC, Richard87 commented
> Added some suggestions and comments. We must also add ScaledObject to the radix-operator clusterrole (all verbs), and to the radix-api and radix-app-admin-envs clusterroles (get, list, watch) if radix-api needs to read the ScaledObject.

Fixed, added `get,list,watch` to app admins and app readers (in `-envs` cluster roles), and `get,list,create,update,patch,delete,watch` to  Radix Operator

2024-05-16 06:42 UTC, Richard87 commented on pkg/apis/radixvalidators/validate_ra_test.go
> +			[]error{radixvalidators.ErrMinReplicasGreaterThanMaxReplicas, radixvalidators.ErrMinReplicasGreaterThanMaxReplicas},
Fixed, was a bug :)

2024-05-16 06:43 UTC, Richard87 commented on pkg/apis/deployment/scaledobject.go
> +			Advanced:        &kedav1.AdvancedConfig{RestoreToOriginalReplicaCount: true},
Will merge and release this before the Operator https://github.com/equinor/radix-api/pull/625

2024-05-16 10:38 UTC, nilsgstrabo approved these changes

2024-05-16 10:40 UTC, merged