add runtime architecture to RA and RD
equinor/radix-operator pull request #1126
Opened 2024-06-03 14:09 UTC by nilsgstrabo

- Added Runtime struct to RadixApplication components and jobs in common and environment config. Runtime has one prop, Architecture, which can be amd64 (the default) or arm64
- Configure job and component affinity based on Runtime in RD
- Building arm64 is only supported for BuildKit enabled applications. Validation is performed in pipeline, and will print an error if using arm64 without BuildKit. The build steps are run on respectitve architecture defined for the component or job. 
- Restructured pipeline steps into separate packages

Also deleted BoolPtr in radix-operator with pointers.Ptr from radix-common, and removed some unused code

2024-06-11 13:42 UTC, satr commented on pipeline-runner/steps/applyconfig/step.go
> +		}
It can be simplified with if ... return

2024-06-11 13:55 UTC, nilsgstrabo commented on pipeline-runner/steps/applyconfig/step.go
> +		}
Tried to make it more readable.  Please check again.

2024-06-11 14:25 UTC, satr commented on pipeline-runner/steps/build/build_acr.go
> +	job := buildContainerImageBuildingJob(rr, pipelineInfo, buildSecrets, hash, nil, buildComponentImages...)
Send explicit runtime?

2024-06-11 14:26 UTC, satr commented on pipeline-runner/internal/tekton/tekton.go
> +					Affinity:      utils.GetAffinityForPipelineJob(nil),
Send explicit runtime?

2024-06-11 14:27 UTC, satr commented on pkg/apis/job/kubejob.go
> +					Affinity:      utils.GetAffinityForPipelineJob(nil),
Send explicit runtime?

2024-06-11 14:37 UTC, satr commented on pkg/apis/deployment/jobschedulercomponent.go
> +	return nil
Return runtime explicitly?

2024-06-11 14:50 UTC, Richard87 requested changes
tinye comments

2024-06-11 14:50 UTC, Richard87 commented on pipeline-runner/steps/promote/errors.go
> +// NonExistingToEnvironment From environment does not exist
```suggestion
// NonExistingToEnvironment To environment does not exist
```

2024-06-11 14:56 UTC, satr commented on pkg/apis/utils/affinity.go
> +						MatchExpressions: getNodeSelectorRequirementsForRuntimeEnvironment(nil),
Explicitly define runtime?

2024-06-11 14:56 UTC, satr commented on pkg/apis/utils/affinity.go
> +						MatchExpressions: getNodeSelectorRequirementsForRuntimeEnvironment(nil),
Explicitly define runtime?

2024-06-12 06:31 UTC, nilsgstrabo commented on pipeline-runner/steps/build/build_acr.go
> +	job := buildContainerImageBuildingJob(rr, pipelineInfo, buildSecrets, hash, nil, buildComponentImages...)
done

2024-06-12 06:31 UTC, nilsgstrabo commented on pipeline-runner/internal/tekton/tekton.go
> +					Affinity:      utils.GetAffinityForPipelineJob(nil),
done

2024-06-12 06:31 UTC, nilsgstrabo commented on pkg/apis/job/kubejob.go
> +					Affinity:      utils.GetAffinityForPipelineJob(nil),
done

2024-06-12 06:32 UTC, nilsgstrabo commented on pkg/apis/utils/affinity.go
> +						MatchExpressions: getNodeSelectorRequirementsForRuntimeEnvironment(nil),
done

2024-06-12 06:32 UTC, nilsgstrabo commented on pkg/apis/utils/affinity.go
> +						MatchExpressions: getNodeSelectorRequirementsForRuntimeEnvironment(nil),
done

2024-06-12 07:24 UTC, Richard87 approved these changes

2024-06-12 08:32 UTC, merged