add-cluster-cleanup-routine
equinor/radix-operator pull request #1205
Opened 2024-10-04 14:45 UTC by satr

2024-10-07 10:37 UTC, nilsgstrabo requested changes
Added some comments that we can discuss

2024-10-07 11:59 UTC, satr commented on radix-operator/main.go
> +	var app *App
Removed

2024-10-07 11:59 UTC, satr commented on radix-operator/main.go
> +	app.schedulers = app.createSchedulers(ctx)
Moved

2024-10-07 12:03 UTC, satr commented on radix-operator/main.go
> +	g.Go(func() error {
Fixed

2024-10-07 12:05 UTC, satr commented on radix-operator/scheduler/task_scheduler.go
> +func NewTaskScheduler(ctx context.Context, task tasks.Task, scheduleSpec string) (TaskScheduler, error) {
Renamed

2024-10-08 13:41 UTC, satr commented on pkg/apis/utils/environments.go
> +func UpdateRadixEnvironmentStatus(ctx context.Context, radixClient versioned.Interface, radixApplication *v1.RadixApplication, radixEnvironment *v1.RadixEnvironment, time v2.Time) error {
Moved

2024-10-08 13:41 UTC, satr commented on pkg/apis/applicationconfig/applicationconfig.go
> +func (app *ApplicationConfig) handleOrphanedEnvironments(ctx context.Context, syncTime metav1.Time) error {
Fixed

2024-10-08 13:41 UTC, satr commented on pkg/apis/radix/v1/radixenvironmenttypes.go
> +	OrphanedTimestamp string `json:"orphanedTimestamp" yaml:"orphanedTimestamp"`
Changed

2024-10-08 13:42 UTC, satr commented on radix-operator/application/handler.go
> +	err = applicationConfig.OnSync(ctx, metav1.NewTime(time.Now().UTC()))
Removed

2024-10-08 13:44 UTC, satr commented on pkg/apis/defaults/environment_variables.go
> +	RadixOrphanedEnvironmentsCleanupCronVariable = "RADIXOPERATOR_ORPHANED_ENVIRONMENTS_CLEANUP_CRONE"
Fixed

2024-10-08 13:47 UTC, satr commented on radix-operator/scheduler/task_scheduler.go
> +	log.Ctx(ctx).Info().Msgf("Created schedule %s for the task %s", scheduleSpec, task.String())
Moved

2024-10-08 13:47 UTC, satr commented on radix-operator/main.go
> +		app.stopSchedulers()
Fixed

2024-10-10 10:18 UTC, nilsgstrabo reviewed
Added a few comments that we can discuss

2024-10-10 10:18 UTC, nilsgstrabo commented on charts/radix-operator/values.yaml
> +  orphanedEnvironmentsRetentionPeriod: 24h
Should we use a higher default, e.g. 7 days (168 hours)?

2024-10-11 08:26 UTC, satr commented on pkg/apis/kube/radix_environment.go
> +func (kubeutil *Kube) ListEnvironmentsWithSelector(ctx context.Context, labelSelectorString string) ([]*radixv1.RadixEnvironment, error) {
Removed

2024-10-11 08:28 UTC, satr commented on pkg/apis/radix/v1/radixenvironmenttypes.go
> +	OrphanedTimestamp *metav1.Time `json:"orphanedTimestamp" yaml:"orphanedTimestamp"`
Fixed

2024-10-11 08:42 UTC, nilsgstrabo approved these changes

2024-10-11 08:43 UTC, merged