feat: Add Healtchchecks to RadixConfig
equinor/radix-operator pull request #1234
Opened 2024-12-02 12:14 UTC by Richard87

2024-12-10 12:05 UTC, nilsgstrabo requested changes
Added a few suggestions that we should discuss

2024-12-10 12:05 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhealthchecktypes.go
> +	FailureThreshold *int32 `json:"failureThreshold,omitempty"`
Why not use the same data type and non-pointer as in corev1.Probe? I don't think we need to define defaults since this is something Kubernetes will handle.

2024-12-10 12:05 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhealthchecktypes.go
> +	// TerminationGracePeriodSeconds *int64 `json:"terminationGracePeriodSeconds,omitempty"`
```suggestion
```
Suggest we remove this if we don't intend to use it

2024-12-10 12:05 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhealthchecktypes.go
> +		// TerminationGracePeriodSeconds: rp.TerminationGracePeriodSeconds,
```suggestion
```
Suggest we remove this if we don't intend to use it

2024-12-10 12:05 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixhealthchecktypes.go
> +type RadixProbeHTTPGetAction struct {
Shoudl we use the same data types for fields as in the corev1 struct? Goes for the other probe actions as well

2024-12-10 12:49 UTC, Richard87 commented on pkg/apis/radix/v1/radixhealthchecktypes.go
> +	// TerminationGracePeriodSeconds *int64 `json:"terminationGracePeriodSeconds,omitempty"`
added todo

2024-12-10 12:50 UTC, Richard87 commented on pkg/apis/radix/v1/radixapptypes.go
> +type RadixHealthChecks struct {
fixed

2024-12-10 13:09 UTC, Richard87 commented on pkg/apis/radix/v1/radixhealthchecktypes.go
> +		// TerminationGracePeriodSeconds: rp.TerminationGracePeriodSeconds,
agreed, fixed

2024-12-10 13:24 UTC, Richard87 commented on pkg/apis/radix/v1/radixhealthchecktypes.go
> +type RadixProbeHTTPGetAction struct {
agreed

2024-12-11 13:52 UTC, nilsgstrabo approved these changes

2024-12-11 14:51 UTC, merged