Validate jobs in RadixApplication
equinor/radix-operator pull request #521
Opened 2021-02-23 14:56 UTC by nilsgstrabo

- validates RadixApplication configuration

2021-02-23 19:58 UTC, satr requested changes
Needs couple corrections and some suggestions

2021-02-23 19:58 UTC, satr commented on pkg/apis/radixvalidators/validate_ra.go
> +		return SchedulerPortCannotBeEmptyForJobError(job.Name)
It should be `PayloadPathCannotBeEmptyForJobError`

2021-02-23 19:58 UTC, satr commented on pkg/apis/radixvalidators/validate_ra.go
> +func SchedulerPortCannotBeEmptyForJobError(job string) error {
Suggestion to use argument name `name` or `jobName` for consistency

2021-02-23 19:58 UTC, satr commented on pkg/apis/radixvalidators/validate_ra.go
> +func PayloadPathCannotBeEmptyForJobError(job string) error {
Suggestion to use argument name `name` or `jobName` for consistency

2021-02-23 19:58 UTC, satr commented on pkg/apis/radixvalidators/validate_ra.go
> +				errs = append(errs, ComponentWithDynamicTagRequiresTagInEnvironmentConfig(job.Name))
Suggestion to rename to `ResourceWithDynamicTagRequiresTagInEnvironmentConfig`
and correct its message

2021-02-23 19:58 UTC, satr commented on pkg/apis/radixvalidators/validate_ra.go
> +							ComponentWithDynamicTagRequiresTagInEnvironmentConfigForEnvironment(job.Name, environment.Environment))
Suggestion to rename to `ResourceWithDynamicTagRequiresTagInEnvironmentConfigForEnvironment`
and correct its message

2021-02-23 19:58 UTC, satr commented on pkg/apis/radixvalidators/validate_ra.go
> +					if doesEnvExistAndIsMappedToBranch(app, environment.Environment) &&
Optional. `doesEnvExistAndIsMappedToBranch` contains weird `if`

2021-02-23 19:58 UTC, satr commented on pkg/apis/radixvalidators/validate_ra.go
> +		err := validateRequiredResourceName("component name", job.Name)
"_job_ name"

2021-02-23 19:58 UTC, satr commented on pkg/apis/radixvalidators/validate_ra_test.go
> +		{"payload is empty struct", radixvalidators.SchedulerPortCannotBeEmptyForJobError(validRAFirstJobName), func(ra *v1.RadixApplication) {
`SchedulerPortCannotBeEmptyForJobError` should be `SchedulerPayloadCannotBeEmptyForJobError`

2021-02-23 19:58 UTC, satr commented on pkg/apis/radixvalidators/validate_ra_test.go
> +		{"payload path is empty string", radixvalidators.SchedulerPortCannotBeEmptyForJobError(validRAFirstJobName), func(ra *v1.RadixApplication) {
`SchedulerPortCannotBeEmptyForJobError` should be `PayloadPathCannotBeEmptyForJobError`

2021-02-23 19:58 UTC, satr commented on pkg/apis/radixvalidators/validate_ra_test.go
> +	type setVolumeMounts func(*v1.RadixApplication, []v1.RadixVolumeMount)
Suggested name `setVolumeMountsFunc`

2021-02-23 20:31 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra.go
> +		return SchedulerPortCannotBeEmptyForJobError(job.Name)
fixed

2021-02-23 20:32 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra.go
> +func SchedulerPortCannotBeEmptyForJobError(job string) error {
fixed

2021-02-23 20:32 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra.go
> +func PayloadPathCannotBeEmptyForJobError(job string) error {
fixed

2021-02-23 20:39 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra.go
> +					if doesEnvExistAndIsMappedToBranch(app, environment.Environment) &&
Is it the line break you refer to?

2021-02-23 20:43 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra_test.go
> +		{"payload is empty struct", radixvalidators.SchedulerPortCannotBeEmptyForJobError(validRAFirstJobName), func(ra *v1.RadixApplication) {
fixed

2021-02-23 20:43 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra_test.go
> +		{"payload path is empty string", radixvalidators.SchedulerPortCannotBeEmptyForJobError(validRAFirstJobName), func(ra *v1.RadixApplication) {
fixed

2021-02-23 20:43 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra_test.go
> +	type setVolumeMounts func(*v1.RadixApplication, []v1.RadixVolumeMount)
fixed

2021-02-23 20:45 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra.go
> +		err := validateRequiredResourceName("component name", job.Name)
fixed

2021-02-24 08:21 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra.go
> +				errs = append(errs, ComponentWithDynamicTagRequiresTagInEnvironmentConfig(job.Name))
agreed to keep as is

2021-02-24 08:22 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra.go
> +							ComponentWithDynamicTagRequiresTagInEnvironmentConfigForEnvironment(job.Name, environment.Environment))
agreed to keep as is

2021-02-24 08:25 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra.go
> +					if doesEnvExistAndIsMappedToBranch(app, environment.Environment) &&
agreed to keep as is

2021-02-24 08:56 UTC, satr approved these changes

2021-02-24 09:37 UTC, merged