72391 job scheduler part 2 fix
equinor/radix-operator pull request #532
Opened 2021-03-15 12:27 UTC by nilsgstrabo

2021-03-15 15:33 UTC, satr requested changes

2021-03-15 15:33 UTC, satr commented on pkg/apis/deployment/radixcomponentname.go
> +	return false
`return t.findInDeploymentSpecJobList(rd) != nil` - maybe?

2021-03-15 15:33 UTC, satr commented on pkg/apis/kube/kube.go
> +	RadixJobTypeJobSchedule      = "job-schedule"
Correct name? schedule or schedule**r** (I was not sure)
Used in `radix-job-scheduler`
![image](https://user-images.githubusercontent.com/702860/111178011-0bdf0880-85ab-11eb-9c9c-3c60aed80ff3.png)

2021-03-15 15:33 UTC, satr commented on pkg/apis/kube/roles.go
> +func GetRole(appName, roleName, namespace string, apiGroups, resources, verbs []string, customLabels *map[string]string) *auth.Role {
Not used (created for rbac logic, which was removed)

2021-03-15 15:37 UTC, nilsgstrabo commented on pkg/apis/deployment/radixcomponentname.go
> +	return false
Agree. Fixed

2021-03-15 15:39 UTC, nilsgstrabo commented on pkg/apis/kube/kube.go
> +	RadixJobTypeJobSchedule      = "job-schedule"
Perhaps "job-scheduler" is more correct. I have changed it.

2021-03-15 15:40 UTC, nilsgstrabo commented on pkg/apis/kube/roles.go
> +func GetRole(appName, roleName, namespace string, apiGroups, resources, verbs []string, customLabels *map[string]string) *auth.Role {
Removed

2021-03-15 15:50 UTC, satr commented on pkg/apis/deployment/radixcomponentname.go
> +	return false
I ment:
```
func (t RadixComponentName) ExistInDeploymentSpecJobList(rd *v1.RadixDeployment) bool {
	return t.findInDeploymentSpecJobList(rd) != nil 
}
```

2021-03-15 16:50 UTC, nilsgstrabo commented on pkg/apis/deployment/radixcomponentname.go
> +	return false
Of course. Fixed

2021-03-16 08:05 UTC, satr approved these changes

2021-03-18 07:47 UTC, merged