54867 env var editable in radix console
equinor/radix-operator pull request #587
Opened 2021-07-30 13:13 UTC by satr

2021-08-12 07:45 UTC, nilsgstrabo commented on pkg/apis/kube/environment_variables.go
> +		statusError := err.(*k8sErrors.StatusError)
k8serrors ha a helper function for checking if an error is of type StatusError and the Reason is NotFound => k8serrors.IsNotFound(err)

You should be able to change it to
```
if err != nil && !k8sErrors.IsNotFound(err) {
	return nil, err
}
```

2021-08-12 09:00 UTC, nilsgstrabo commented on pkg/apis/deployment/environmentvariables_test.go
> +	envVar1 := getEnvVarsFromRadixConfig(radixConfigEnvVariableMap, envVarsConfigMap, envVarMetadataMap)
I don't understand why this test loops 100 times. Would be a more useful test if if checked that the result is in expected sorted order, and that the ValueFrom in EnvVar is correctly set

2021-08-12 09:37 UTC, nilsgstrabo commented on pkg/apis/deployment/deployment.go
> +	envVarConfigMap, envVarsMetadataConfigMap, err := deploy.kubeutil.GetOrCreateEnvVarsConfigMapAndMetadataMap(deploy.radixDeployment.GetNamespace(), deploy.radixDeployment.GetName(), component.GetName
Can this be moved into the createOrUpdateDeployment method? It is not used anywhere else.

2021-08-12 09:49 UTC, nilsgstrabo commented on pkg/apis/deployment/kubedeployment.go
> +	deploy.kubeutil.ApplyConfigMap(deploy.radixDeployment.Namespace, currentEnvVarsConfigMap, desiredEnvVarsConfigMap)
I found it difficult to understand where in the code the configmaps were updated.
Is it possible to somehow refactor it into a createOrUpdateEnvVarConfigMaps and use the returned configmap as source for building []EnvVar?

It wasn't intuitive to me that getEnvironmentVariablesForRadixOperator would modify the arguments that is passed to it. Perhaps it is cleaner to first "create or update configMap" and the pass the updated configmap to getEnvironmentVariablesForRadixOperator, which then calls getEnvironmentVariablesFrom. getEnvironmentVariablesFrom should then use the configMap as source for environment variables instead of v1.EnvVarsMap from deployComponent.GetEnvironmentVariables().

2021-08-12 10:01 UTC, nilsgstrabo commented on pkg/apis/deployment/environmentvariables.go
> +func removeFromConfigMapEnvVarsNotExistingInRadixconfig(envVarsMap v1.EnvVarsMap, envVarConfigMap *corev1.ConfigMap) {
This function is not used anywhere. Can be removed.

2021-08-12 10:08 UTC, nilsgstrabo commented on pkg/apis/deployment/environmentvariables.go
> +func getEnvVarsFromRadixConfig(radixConfigEnvVars v1.EnvVarsMap, envVarConfigMap *corev1.ConfigMap, envVarMetadataMap map[string]v1.EnvVarMetadata) []corev1.EnvVar {
How are deleted environment variables in RD handled in configMap?

2021-08-12 10:14 UTC, nilsgstrabo commented on pkg/apis/kube/config_maps.go
> +func (kubeutil *Kube) ApplyConfigMap(namespace string, currentConfigMap, desiredConfigMap *corev1.ConfigMap) error {
Missing unit test

2021-08-12 10:15 UTC, nilsgstrabo commented on pkg/apis/kube/config_maps.go
> +func (kubeutil *Kube) UpdateConfigMap(namespace string, configMaps ...*corev1.ConfigMap) error {
Missing unit test

2021-08-12 10:28 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixapptypes.go
> +func DeepCopyEnvVarsMetadata(envVarsMetadata EnvVarMetadata) EnvVarMetadata {
Can't see where this is used

2021-08-12 10:40 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixapptypes.go
> +type RadixConfigMapType string
Feels unnatural to define RadixConfigMapType here. It is not part of the radix CRDs.

2021-08-12 10:42 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixapptypes.go
> +const (
Perhaps move the constants to environment_variables in pkg/apis/kube? Only used there.

2021-08-12 10:44 UTC, nilsgstrabo commented on pkg/apis/radix/v1/radixapptypes.go
> +type EnvVarMetadata struct {
Same as for RadixConfigMapType. Feels unnatural to have it here

2021-08-12 10:47 UTC, nilsgstrabo commented on pkg/apis/test/utils.go
> +func (tu *Utils) ApplyRadixDeploymentEnvVarsConfigMaps(rd *v1.RadixDeployment) map[string]*corev1.ConfigMap {
Can't see where this is used. Remove it?

2021-08-12 10:48 UTC, nilsgstrabo requested changes
Just a a few things we should discuss

2021-08-16 14:01 UTC, satr commented on pkg/apis/kube/environment_variables.go
> +		statusError := err.(*k8sErrors.StatusError)
Fixed.

2021-08-16 14:02 UTC, satr commented on pkg/apis/deployment/environmentvariables_test.go
> +	envVar1 := getEnvVarsFromRadixConfig(radixConfigEnvVariableMap, envVarsConfigMap, envVarMetadataMap)
Two years old test. I'm not sure about loop. Fixed as you suggested.

2021-08-16 14:02 UTC, satr commented on pkg/apis/deployment/environmentvariables.go
> +	if radixSecretNames != nil && len(radixSecretNames) > 0 {
Fixed

2021-08-16 14:03 UTC, satr commented on pkg/apis/deployment/environmentvariables.go
> +func removeFromConfigMapEnvVarsNotExistingInRadixconfig(envVarsMap v1.EnvVarsMap, envVarConfigMap *corev1.ConfigMap) {
Removed

2021-08-16 14:07 UTC, satr commented on pkg/apis/deployment/environmentvariables.go
> +func getEnvVarsFromRadixConfig(radixConfigEnvVars v1.EnvVarsMap, envVarConfigMap *corev1.ConfigMap, envVarMetadataMap map[string]v1.EnvVarMetadata) []corev1.EnvVar {
This is done in `removeFromConfigMapEnvVarsNotExistingInRadixconfig` - restored its usage

2021-08-16 14:14 UTC, satr commented on pkg/apis/radix/v1/radixapptypes.go
> +func DeepCopyEnvVarsMetadata(envVarsMetadata EnvVarMetadata) EnvVarMetadata {
Outdated. Removed.

2021-08-16 14:17 UTC, satr commented on pkg/apis/radix/v1/radixapptypes.go
> +type RadixConfigMapType string
Moved to a file `radixenvironmentvariabletypes.go`

2021-08-16 14:26 UTC, satr commented on pkg/apis/radix/v1/radixapptypes.go
> +const (
Moved to `kube`

2021-08-16 14:26 UTC, satr commented on pkg/apis/radix/v1/radixapptypes.go
> +type EnvVarMetadata struct {
Moved to `kube`

2021-08-16 14:29 UTC, satr commented on pkg/apis/test/utils.go
> +func (tu *Utils) ApplyRadixDeploymentEnvVarsConfigMaps(rd *v1.RadixDeployment) map[string]*corev1.ConfigMap {
Used in `test/utils/ApplyDeployment`. Made it private.

2021-08-19 12:38 UTC, nilsgstrabo commented on pkg/apis/kube/environment_variables.go
> +		statusError := err.(*k8sErrors.StatusError)
You don't even need to cast it to StatusError. Just use err directly in IsNotFound

```
	if err != nil && !k8sErrors.IsNotFound(err) {
		return nil, err
	}
```

2021-08-19 12:47 UTC, nilsgstrabo commented on pkg/apis/deployment/environmentvariables.go
> +func getEnvVarsFromRadixConfig(envVarConfigMap *corev1.ConfigMap, deployComponentEnvVars v1.EnvVarsMap) []corev1.EnvVar {
Is the work RadixConfig a bit misleading? Should it perhaps be getEnvVarsFromConfigMap?

2021-08-19 12:47 UTC, nilsgstrabo submitted a review, later dismissed

2021-08-19 12:57 UTC, satr commented on pkg/apis/kube/environment_variables.go
> +		statusError := err.(*k8sErrors.StatusError)
Fixed

2021-08-19 13:10 UTC, satr commented on pkg/apis/deployment/environmentvariables.go
> +func getEnvVarsFromRadixConfig(envVarConfigMap *corev1.ConfigMap, deployComponentEnvVars v1.EnvVarsMap) []corev1.EnvVar {
Fixed (renamed to `getEnvVars`)

2021-08-20 07:35 UTC, merged