Fix deployment with error during cm creation
equinor/radix-operator pull request #594
Opened 2021-08-24 13:36 UTC by satr

Fixed config-map sync . 
Added error handling for create desired deployment

2021-08-24 17:25 UTC, nilsgstrabo commented on pkg/apis/kube/config_maps.go
> +	createdConfigMap, err := kubeutil.kubeClient.CoreV1().ConfigMaps(namespace).Create(context.TODO(),
You can just return directly. Are there situations where Get returns an error and a configmap, or vice versa; nil error and nil configmap?

2021-08-24 17:28 UTC, nilsgstrabo commented on pkg/apis/kube/config_maps.go
> +	log.Debugf("Created environment variables ConfigMap  '%s'", configMap.GetName())
Debug message (Create) does not match operation (Get).
Guess you can return directly from the call to Get. Ref comment above

2021-08-24 17:29 UTC, nilsgstrabo requested changes
A few comments related to Get and Create configmap methods

2021-08-24 18:25 UTC, nilsgstrabo approved these changes
A few minor comments, but nothing important

2021-08-25 07:10 UTC, satr commented on pkg/apis/kube/config_maps.go
> +	createdConfigMap, err := kubeutil.kubeClient.CoreV1().ConfigMaps(namespace).Create(context.TODO(),
Fixed

2021-08-25 07:10 UTC, satr commented on pkg/apis/kube/config_maps.go
> +	log.Debugf("Created environment variables ConfigMap  '%s'", configMap.GetName())
Removed

2021-08-25 07:10 UTC, merged