added timeLimitSeconds to radixconfig. passed as ActiveDeadlineSeconds
equinor/radix-operator pull request #639
Opened 2022-01-12 08:23 UTC by magnus-longva-bouvet

2022-01-12 08:23 UTC, magnus-longva-bouvet commented on pkg/apis/deployment/kubedeployment.go
> -	desiredDeployment.Spec.Template.Spec.Containers[0].ImagePullPolicy = corev1.PullAlways
Removed this line because it appears to be duplicated on 183

2022-01-12 08:25 UTC, magnus-longva-bouvet commented on pkg/apis/deployment/kubedeployment.go
> +	timeLimitSeconds := deployComponent.GetTimeLimitSeconds()
If I've understood correctly, this function is the appropriate place to add logic which only applies to either regular components or job components. True?

2022-01-12 09:01 UTC, satr requested changes

2022-01-17 08:56 UTC, satr approved these changes

2022-01-17 13:00 UTC, merged