61455 oauth as a service
equinor/radix-operator pull request #645
Opened 2022-01-20 12:00 UTC by nilsgstrabo

2022-01-21 11:57 UTC, satr requested changes

2022-01-21 14:19 UTC, nilsgstrabo commented on pkg/apis/deployment/deployment.go
> +
fixed

2022-01-21 14:19 UTC, nilsgstrabo commented on pkg/apis/deployment/environmentvariables.go
> +	// return getEnvironmentVariables(appName, envVarsSource, radixDeployment, deployComponent.GetName(), deployComponent.GetSecrets(), deployComponent.IsPublic(), deployComponent.GetPorts(), envVarsCon
fixed

2022-01-21 14:20 UTC, nilsgstrabo commented on pkg/apis/deployment/ingressannotationprovider.go
> +func (o *ingressConfigurationAnnotationProvider) GetAnnotations(component v1.RadixCommonDeployComponent) (map[string]string, error) {
fixed

2022-01-21 14:31 UTC, nilsgstrabo commented on pkg/apis/deployment/radixcomponent.go
> +		return componentAuthentication.DeepCopy(), nil
Removed all else-if to make code more readable (hopefully)

2022-01-21 14:32 UTC, nilsgstrabo commented on pkg/apis/utils/oauth/oauth.go
> +// SanitizePathPrefix adds a leading "/" and strips away any "/" at the end
fixed

2022-01-21 14:58 UTC, nilsgstrabo commented on pkg/apis/defaults/oauth2.go
> +type OAuth2Config interface {
fixed

2022-01-24 08:07 UTC, satr requested changes

2022-01-24 08:07 UTC, satr commented on pkg/apis/utils/oauth/oauth.go
> +// SanitizePathPrefix adds a trailing "/" and strips away any "/" at the end
I would expected something like:
'// SanitizePathPrefix adds a leading "/" and strips away any trailing "/" ' :)

2022-01-24 14:07 UTC, nilsgstrabo commented on pkg/apis/utils/oauth/oauth.go
> +// SanitizePathPrefix adds a trailing "/" and strips away any "/" at the end
fixed

2022-01-24 14:07 UTC, nilsgstrabo commented on pkg/apis/utils/random.go
> +// GenerateRandomKey generates a cryptographically secure random key
moved

2022-01-24 14:10 UTC, satr approved these changes

2022-01-24 14:34 UTC, merged