Make PDB when HPA.MinReplicas > 1
equinor/radix-operator pull request #759
Opened 2022-09-08 13:54 UTC by anneliawa

2022-09-08 14:24 UTC, magnus-longva-bouvet approved these changes

2022-09-20 08:02 UTC, nilsgstrabo requested changes
Added a few comments that must be adressed

2022-09-20 08:02 UTC, nilsgstrabo commented on pkg/apis/deployment/pdb.go
> +func componentShallHavePdb(component v1.RadixCommonDeployComponent) bool {
There is a special condition described in the docs (https://www.radix.equinor.com/references/reference-radix-config/#environmentconfig), when replicas=0 then a HPA is not created.
This condition must also be considered when creating the PDB. When replicas=0, no PDB must be created

2022-09-28 12:42 UTC, nilsgstrabo approved these changes

2022-09-28 12:59 UTC, merged