Removed run-as-non-root
equinor/radix-operator pull request #774
Opened 2022-10-21 10:30 UTC by anneliawa

2022-10-21 15:05 UTC, satr requested changes

2022-10-21 15:05 UTC, satr commented on pkg/apis/deployment/securitycontext.go
> +	return &securityContextBuilder{forceRunAsNonRoot: true}
Argument should not be removed

2022-10-26 10:04 UTC, anneliawa commented on pkg/apis/deployment/securitycontext.go
> +	return &securityContextBuilder{forceRunAsNonRoot: true}
should this still not be removed?

2022-10-26 10:12 UTC, satr commented on pkg/apis/deployment/securitycontext.go
> +	return &securityContextBuilder{forceRunAsNonRoot: true}
As it is decided to remove functionality `forceRunAsNonRoot` - this need to be removed (you did this allredy correctly), as well as arguments in logic it used (and env-var)

2022-10-26 12:58 UTC, satr requested changes
This can be removed https://github.com/equinor/radix-operator/blob/7ae5c7dbb367b98ca404eba21bde1c2069ab4604/pkg/apis/defaults/environment_variables.go#L91.
Also any use of `RADIX_DEPLOYMENTS_FORCE_NON_ROOT_CONTAINER`

2022-11-02 08:42 UTC, satr approved these changes

2022-11-02 08:44 UTC, merged