Pipeline result config map is not deleted, but got radixjob as owner-…
equinor/radix-operator pull request #796
Opened 2022-12-07 15:54 UTC by satr

…reference

2022-12-09 08:02 UTC, nilsgstrabo requested changes
Added a few suggestions

2022-12-09 08:02 UTC, nilsgstrabo commented on pkg/apis/kube/config_maps.go
> +func (kubeutil *Kube) GetConfigMapListForLabels(namespace string, requirements ...labels.Requirement) ([]corev1.ConfigMap, error) {
Rename to ListConfigMapsWithSelector(namespace string, labelSelector string) ([]corev1.ConfigMap, error)

2022-12-09 08:36 UTC, satr commented on pkg/apis/job/job.go
> +func (job *Job) getRadixJobNameSet(namespace string) (map[string]bool, error) {
Fixed

2022-12-09 09:12 UTC, satr commented on pkg/apis/job/kubejob.go
> +	resultConfigMaps, err := job.kubeutil.GetConfigMapListForLabels(jobNamespace, *radixJobNameReq, *pipelineResultConfigMapReq)
Fixed

2022-12-09 09:12 UTC, satr commented on pkg/apis/kube/config_maps.go
> +func (kubeutil *Kube) GetConfigMapListForLabels(namespace string, requirements ...labels.Requirement) ([]corev1.ConfigMap, error) {
Renamed

2022-12-12 14:34 UTC, nilsgstrabo approved these changes

2022-12-12 14:35 UTC, merged