199772 Move SSH private key from RR to Secret
equinor/radix-operator pull request #848
Opened 2023-03-17 09:41 UTC by anneliawa

2023-03-17 11:39 UTC, magnus-longva-bouvet commented on radix-operator/registration/controller.go
> +				// TODO: Configmap was deleted, but not recreated.
This scenario has happened at least once during testing. Why does this some times happen, and how can we recover from it? The consequence is that a user clicks the "Regenerate deploy key button", but a new key does _not_ appear in web-console. In order to get a new deploy key, the user would need to make some arbitrary change to RR and trigger a resync

2023-03-17 11:40 UTC, magnus-longva-bouvet commented on pkg/apis/utils/keyGen.go
This file is pretty much copy-pasted and moved from radix-api

2023-03-17 12:42 UTC, nilsgstrabo commented on radix-operator/registration/controller.go
> +				// TODO: Configmap was deleted, but not recreated.
I don't know the details, but for some reason a deleted object is either the object itself, or a cache.DeletedFinalStateUnknown. This struct type has an .Obj property which is the actual deleted object.
You need to try casting to both types.

You can see how it is used here: [https://github.com/equinor/radix-operator/blob/2e77bd637ac19167fd5b3b56f8c4605f28aaa079/radix-operator/common/controller.go#L222](https://github.com/equinor/radix-operator/blob/2e77bd637ac19167fd5b3b56f8c4605f28aaa079/radix-operator/common/controller.go#L222)

2023-03-17 14:19 UTC, nilsgstrabo commented on pkg/apis/utils/keyGen.go
Should consider switching to ed22519 ("crypto/ed25519") instead of rsa?

2023-04-25 08:29 UTC, nilsgstrabo requested changes
Added some suggestions and one issue that must be fixed

2023-04-25 08:29 UTC, nilsgstrabo commented on pkg/apis/defaults/configmaps.go
> +	GitPrivateKeySecretKey            = "id-rsa"
```suggestion
	GitPrivateKeySecretKey            = "id_rsa"
```

The existing key is "id_rsa" (underscore). GitPrivateKeySecretKey must use the same key name to prevent regeneration of all keys.

2023-04-25 08:29 UTC, nilsgstrabo commented on pkg/apis/defaults/configmaps.go
> +	GitPublicKeyConfigMapKey          = "public-key"
```suggestion
	GitPublicKeyConfigMapKey          = "public_key"
```
Use underscore to align with name of private key

2023-04-25 12:37 UTC, nilsgstrabo approved these changes

2023-04-25 12:37 UTC, merged