68 reader role
equinor/radix-operator pull request #892
Opened 2023-07-18 10:14 UTC by anneliawa

2023-07-18 13:31 UTC, satr requested changes

2023-07-18 13:31 UTC, satr commented on pkg/apis/defaults/roles.go
> +
Word `manage` can be removed

2023-07-18 14:46 UTC, satr approved these changes

2023-07-19 06:46 UTC, satr approved these changes

2023-07-19 07:25 UTC, magnus-longva-bouvet approved these changes

2023-07-19 07:26 UTC, merged