Removed antiaffinity from jobs, reduced builder resources
equinor/radix-operator pull request #926
Opened 2023-09-08 13:42 UTC by satr

2023-09-11 14:21 UTC, nilsgstrabo requested changes

2023-09-11 14:21 UTC, nilsgstrabo commented on pkg/apis/batch/kubejob.go
> +	// if !radixlabels.GetRadixBatchDescendantsSelector(jobComponent.GetName()).Matches(labels.Set(payloadSecret.GetLabels())) {
Why is this code commented out?

2023-09-11 14:23 UTC, satr commented on pkg/apis/batch/kubejob.go
> +	// if !radixlabels.GetRadixBatchDescendantsSelector(jobComponent.GetName()).Matches(labels.Set(payloadSecret.GetLabels())) {
It should be uncommented. I’ll fix it

2023-09-13 12:12 UTC, satr commented on pkg/apis/batch/kubejob.go
> +	// if !radixlabels.GetRadixBatchDescendantsSelector(jobComponent.GetName()).Matches(labels.Set(payloadSecret.GetLabels())) {
Fixed

2023-09-18 06:52 UTC, nilsgstrabo approved these changes

2023-09-18 07:15 UTC, merged