Update validation of imageTagName in CICD pipeline
equinor/radix-operator pull request #986
Opened 2023-11-24 14:44 UTC by nilsgstrabo

2023-11-28 14:30 UTC, Richard87 requested changes
noen kommentarer

2023-11-28 14:30 UTC, Richard87 commented on charts/radix-operator/Chart.yaml
> +appVersion: 1.45.5
Må bumpes til 7 eller over...

2023-11-28 14:30 UTC, Richard87 commented on pipeline-runner/steps/errors.go
> +	return fmt.Errorf("component %s requires imageTagName to be set in environmentConfig for environment %s or specified as argument to the pipeline job", componentName, envName)
Kan deler av feilmeldingen være statisk slik at Error.Is fungerer?

2023-11-29 08:22 UTC, nilsgstrabo commented on pipeline-runner/steps/errors.go
> +	return fmt.Errorf("component %s requires imageTagName to be set in environmentConfig for environment %s or specified as argument to the pipeline job", componentName, envName)
fixed

2023-11-29 09:38 UTC, nilsgstrabo commented on charts/radix-operator/Chart.yaml
> +appVersion: 1.45.5
fixed

2023-11-29 13:34 UTC, Richard87 approved these changes
godkjent

2023-11-29 13:59 UTC, merged