115 privateimagehubs dockerfile
equinor/radix-operator pull request #998
Opened 2023-12-01 09:59 UTC by anneliawa

2023-12-01 14:05 UTC, Richard87 requested changes
Liten merknad

2023-12-01 14:05 UTC, Richard87 commented on pipeline-runner/steps/build_acr.go
> +			commandList.AddStrCmd("/usr/bin/buildah login --username %s --password %s %s", auth.Username, auth.Password, registry)
Move password (and username?) to environment variables so they are not visible in the Pod definition

2023-12-04 12:11 UTC, nilsgstrabo commented on pipeline-runner/steps/build_acr.go
> +			commandList.AddStrCmd("/usr/bin/buildah login --username %s --password %s %s", auth.Username, auth.Password, registry)
Fixed. The radix-private_image_hubs secrets is mounted in the build containers and used as authfile for buildah

2023-12-05 07:38 UTC, Richard87 approved these changes
Godkjent

2023-12-05 07:41 UTC, merged