Custom internal alias
equinor/radix-operator pull request #999
Opened 2023-12-01 13:48 UTC by satr

2023-12-05 08:32 UTC, nilsgstrabo commented on pkg/apis/application/application.go
> +func (app Application) updateRadixRegistrationStatus(rr *v1.RadixRegistration, changeStatusFunc func(currStatus *v1.RadixRegistrationStatus)) error {
```suggestion
func (app *Application) updateRadixRegistrationStatus(rr *v1.RadixRegistration, changeStatusFunc func(currStatus *v1.RadixRegistrationStatus)) error {
```
We should use pointer receiver on all methods for Application

2023-12-05 08:41 UTC, nilsgstrabo commented on pkg/apis/alert/alert_test.go
> +	if err := sut.OnSync(); err != nil {
Consider using s.Require().NoError(err) or s.NoError(err)

2023-12-05 09:30 UTC, nilsgstrabo commented on pkg/apis/defaults/k8s/k8s.go
> +	APIVersionNetworking   = "networking.k8s.io/v1"
```suggestion
```
Remove APIVersionNetworking and replace it with call to networkingv1.SchemeGroupVersion.Identifier()

We should also remove other consts that are defined by k8s:
- RbacApiVersion: Replace with rbacv1.SchemeGroupVersion.Identifier()
- RbacApiGroup: Replace with rbacv1.GroupName
- RbacApiConfig is unused: delete
- KindServiceAccount: replace with rbacv1.ServiceAccountKind
- KindGroup: replace with rbacv1.GroupKind

2023-12-05 09:44 UTC, nilsgstrabo commented on pkg/apis/radix/register.go
> +const (
Consider moving GroupName to v1 package

2023-12-05 09:46 UTC, nilsgstrabo commented on pkg/apis/radix/register.go
> +	ResourceRadixDeployment = "radixdeployment"
ResourceRadixDeployment not used. Remove.

2023-12-05 09:54 UTC, nilsgstrabo commented on pkg/apis/applicationconfig/applicationconfig.go
> +	return commonErrors.Concat(errs)
Use errors.Join() from standard errors package.

2023-12-05 11:20 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_ra_test.go
> +		{"dns app alias non existing component", radixvalidators.ComponentForDNSAppAliasNotDefinedError(nonExistingComponent), func(ra *v1.RadixApplication) {
Missing tests for ReservedAppDNSAliases names

2023-12-05 11:23 UTC, nilsgstrabo commented on pkg/apis/radixvalidators/validate_rr.go
> +	ErrInvalidRadixConfigFullName = fmt.Errorf("invalid file name for radixconfig. See https://www.radix.equinor.com/references/reference-radix-config/ for more information")
use errors.New() instead

2023-12-05 11:30 UTC, nilsgstrabo commented on pkg/apis/test/utils.go
> +			panic(err)
Return error instead of panic

2023-12-05 11:30 UTC, nilsgstrabo commented on pkg/apis/test/utils.go
> +			panic(err)
Return error instead of panic

2023-12-05 11:30 UTC, nilsgstrabo commented on pkg/apis/test/utils.go
> +			panic(err)
Return error instead of panic

2023-12-05 11:33 UTC, nilsgstrabo commented on pkg/apis/test/utils.go
> +func AssertError(t *testing.T, expectedError string, err error) {
Use built in asserts

2023-12-05 11:34 UTC, nilsgstrabo commented on pkg/apis/dnsalias/syncer_test.go
> +	expectedError   string
Never user. Remove?

2023-12-05 11:39 UTC, nilsgstrabo commented on pkg/apis/utils/environment_builder_test.go
> +	assert.Equal(t, re.ObjectMeta.Finalizers[0], kube.RadixEnvironmentFinalizer)
These two lines can be replaced with a single assert.ElementsMatch()

2023-12-05 11:45 UTC, nilsgstrabo commented on pkg/apis/utils/application_builder.go
> +func (ap *ApplicationBuilderStruct) WithDNSAlias(dnsAliases ...radixv1.DNSAlias) ApplicationBuilder {
This method should not perform any logic, it should just set DNSAlias to the value supplied.

2023-12-05 11:52 UTC, satr commented on charts/radix-operator/Chart.yaml
> +appVersion: 1.46.1
Fixed

2023-12-05 11:54 UTC, satr commented on Makefile
> +	yq eval '.spec.versions[0].schema.openAPIV3Schema' -ojson $(CRD_CHART_DIR)radixdnsalias.yaml > $(JSON_SCHEMA_DIR)radixdnsalias.json
Fixed

2023-12-05 12:13 UTC, satr commented on pipeline-runner/steps/build_test.go
> +func getDNSAliasConfig() *dnsalias.DNSConfig {
fixed

2023-12-05 13:30 UTC, nilsgstrabo commented on pkg/apis/kube/kube.go
> +	ManagedByRadixDNSAliasIngressAnnotation          = "radix.equinor.com/managed-by-radix-dns-alias"
ManagedByRadixDNSAliasIngressAnnotation annotation is set on ingress objects, but is not used after that. What is the intention for the annotation?

2023-12-05 13:30 UTC, nilsgstrabo commented on pkg/apis/kube/kube.go
> +	RadixDNSAliasFinalizer                           = "radix.equinor.com/dnsalias-finalizer"
Should we move these to their own const block with comment `// Radix finalizers`?

2023-12-05 14:06 UTC, nilsgstrabo commented on pkg/apis/kube/ingress.go
> +func (kubeutil *Kube) GetIngressesWithSelector(namespace string, labelSelectorString string) ([]*networkingv1.Ingress, error) {
GetIngressesWithSelector does not use lister when available. This breaks the pattern for all other kube methods. If we require non-cached data we should query the K8S API directly with kubeclient.

2023-12-06 07:21 UTC, nilsgstrabo commented on pkg/apis/applicationconfig/applicationconfig.go
> +func (app *ApplicationConfig) getPortForDNSAlias(dnsAlias radixv1.DNSAlias) (int32, error) {
Move function to dns_alias.go

2023-12-06 07:48 UTC, nilsgstrabo commented on pkg/apis/applicationconfig/dns_alias_test.go
> +func Test_ValidateApplicationCanBeAppliedWithDNSAliases(t *testing.T) {
This test is technically testing the RA validation and should included in tests in radixvalidators package

2023-12-06 07:49 UTC, nilsgstrabo commented on pkg/apis/applicationconfig/errors.go
> +}
These errors functions are only used by tests. Also, they are duplicate of functions defined in radixvalidators

2023-12-06 07:53 UTC, nilsgstrabo commented on pkg/apis/applicationconfig/imagehubsecret.go
> +func UpdatePrivateImageHubsSecretsPassword(kubeutil *kube.Kube, appName, server, password string) error {
This function is only used by radix-api. We should move it there, along with related tests.

2023-12-06 07:53 UTC, nilsgstrabo commented on pkg/apis/applicationconfig/imagehubsecret.go
> +func GetPendingPrivateImageHubSecrets(kubeUtil *kube.Kube, appName string) ([]string, error) {
This function is only used by radix-api. We should move it there, along with related tests.

2023-12-06 07:58 UTC, nilsgstrabo commented on pkg/apis/applicationconfig/dns_alias.go
> +func (app *ApplicationConfig) createOrUpdateDNSAliases() error {
method name only implies create or update of DNS aliases, but is also perform deletions. Would it be more correct to call it syncDNSAliases=

2023-12-06 08:23 UTC, nilsgstrabo commented on pkg/apis/deployment/environmentvariables_test.go
> +			log.Error(err)
Use require.NoError to fail test instead of log

2023-12-06 08:40 UTC, nilsgstrabo commented on pkg/apis/dnsalias/syncer.go
> +		if admissionWebhookErrorMatcher := admissionWebhookErrorExpression.FindStringSubmatch(err.Error()); len(admissionWebhookErrorMatcher) == 5 {
I don't think we should try to parse the error message from a regexp. The error is external and can change any time we update to newer versions of nginx. Just return the raw error

2023-12-06 09:06 UTC, nilsgstrabo commented on pkg/apis/dnsalias/syncer.go
> +func (s *syncer) syncAlias() error {
The flow would be easier to follow if was was something like:

```
ing := buildIngress(...)
err := applyIngress(ing...)
err := syncOAuthProxyIngress(ing...)
```
where syncOAuthProxyIngress is something like:

```
if !oauthEnabled {
    delete the oauth ingress if existing
}

ing := buildOauthIng(sourceIng)
applyIngresS(ing...)
```

2023-12-06 09:53 UTC, nilsgstrabo commented on pkg/apis/dnsalias/status.go
> +		return fmt.Errorf("unable to deserealise status from annotation: %w", err)
```suggestion
		return fmt.Errorf("unable to deserialize status from annotation: %w", err)
```

2023-12-06 09:54 UTC, nilsgstrabo commented on pkg/apis/dnsalias/status.go
> +		return fmt.Errorf("failed to sync status: %v", err)
```suggestion
		return fmt.Errorf("failed to sync status: %w", err)
```

2023-12-06 09:57 UTC, nilsgstrabo commented on pkg/apis/environment/environment.go
> +func (env *Environment) handleDeletedRadixEnvironment(re *v1.RadixEnvironment) (bool, error) {
Add tests for RE with DeletionTimestamp - resources deleted, finalizer removed etc

2023-12-06 10:14 UTC, nilsgstrabo commented on radix-operator/dnsalias/controller.go
> +			logger.Errorf("failed to re-sync RadixDNSAlias %s. Error: %v", radixDNSAlias.GetName(), err)
```suggestion
			logger.Errorf("failed to enqueue RadixDNSAlias %s: %w", radixDNSAlias.GetName(), err)
```

2023-12-06 10:57 UTC, nilsgstrabo commented on charts/radix-operator/templates/radix-operator-rbac.yaml
>    verbs:
Should also grant radix-api get and list permission on radixdnsalias

2023-12-06 11:34 UTC, nilsgstrabo requested changes
Completed review. See comments

2023-12-07 09:39 UTC, satr commented on charts/radix-operator/templates/radix-operator-rbac.yaml
>    verbs:
It will be fixed with change of radix-api - we add ClusterRole per an app for list of aliases, with binding to the app-admin

2023-12-07 13:54 UTC, satr commented on pkg/apis/applicationconfig/dns_alias.go
> +func (app *ApplicationConfig) createOrUpdateDNSAliases() error {
Renamed the method and refactored to be more clear. It was also fixed to validate aliases belonging to another app (this condition did not work), added more unit-tests

2023-12-07 14:02 UTC, satr commented on pkg/apis/applicationconfig/dns_alias_test.go
> +func Test_ValidateApplicationCanBeAppliedWithDNSAliases(t *testing.T) {
Moved to ra-validation tests

2023-12-11 11:03 UTC, satr commented on pkg/apis/deployment/environmentvariables_test.go
> +			log.Error(err)
Fixed

2023-12-11 11:05 UTC, satr commented on pkg/apis/deployment/radixcomponent_test.go
> +func TestGetRadixComponentsForEnv_ListOfDNSAliasesForComponent_GetListOfAliases(t *testing.T) {
Deleted

2023-12-12 10:13 UTC, satr commented on pkg/apis/dnsalias/syncer.go
> +func (s *syncer) syncAlias() error {
Fixed

2023-12-12 10:15 UTC, satr commented on pkg/apis/dnsalias/syncer_test.go
> +	expectedError   string
Deleted dnsAlias

2023-12-12 10:18 UTC, satr commented on pkg/apis/dnsalias/syncer_test.go
> +			commonTest.AssertError(s.T(), ts.expectedError, err)
Removed

2023-12-12 11:26 UTC, satr commented on pkg/apis/applicationconfig/imagehubsecret.go
> +func UpdatePrivateImageHubsSecretsPassword(kubeutil *kube.Kube, appName, server, password string) error {
Moved to radix-api

2023-12-12 11:52 UTC, satr commented on radix-operator/main.go
> +	const waitForChildrenToSync = true
fixed

2023-12-12 11:52 UTC, satr commented on radix-operator/main.go
> +	const waitForChildrenToSync = true
fixed

2023-12-12 11:52 UTC, satr commented on radix-operator/main.go
> +	const waitForChildrenToSync = true
fixed

2023-12-12 11:54 UTC, satr commented on radix-operator/main.go
> +	const waitForChildrenToSync = true
fixed

2023-12-12 11:54 UTC, satr commented on radix-operator/main.go
> +	const waitForChildrenToSync = true
replay

2023-12-12 11:54 UTC, satr commented on radix-operator/main.go
> +	const waitForChildrenToSync = true
fixed

2023-12-12 11:54 UTC, satr commented on radix-operator/main.go
> +	const waitForChildrenToSync = true
fixed

2023-12-12 11:55 UTC, satr commented on radix-operator/main.go
> +	const waitForChildrenToSync = true
fixed

2023-12-12 12:02 UTC, satr commented on radix-operator/main.go
> +func setLogLevel(logLevel apiconfig.LogLevel) {
Fixed

2023-12-12 12:26 UTC, satr commented on pkg/apis/applicationconfig/errors.go
> +}
Fixed

2023-12-12 12:35 UTC, satr commented on pkg/apis/dnsalias/syncer.go
> +func (s *syncer) createOrUpdateOAuthProxyIngressForComponentIngress(componentAuthentication *radixv1.Authentication, namespace string, aliasSpec radixv1.RadixDNSAliasSpec, radixDeployComponent radixv
Fixed

2023-12-12 12:38 UTC, satr commented on pkg/apis/dnsalias/syncer.go
> +		if admissionWebhookErrorMatcher := admissionWebhookErrorExpression.FindStringSubmatch(err.Error()); len(admissionWebhookErrorMatcher) == 5 {
I did not find better alternative not to show another application name in the error. If this specific error is not matching to the regex pattern, the original error is shown.

2023-12-15 06:59 UTC, nilsgstrabo commented on pkg/apis/radix/v1/register.go
> +	Group:   "radix.equinor.com",
Extract string to const (following the pattern in kubernetes)

```
const GroupName = "radix.equinor.com"
```

2023-12-15 07:04 UTC, nilsgstrabo commented on pkg/apis/alert/alert_test.go
> +	}
```suggestion
	err := s.radixClient.RadixV1().RadixRegistrations().Create(context.Background(), rr, metav1.CreateOptions{})
	s.Require().NoError(err)
```
No need to wrap this in `if` block.

2023-12-15 07:09 UTC, nilsgstrabo commented on pkg/apis/application/rolebinding.go
>  			Kind:       "RoleBinding",
Use const KindRoleBinding from defaults/k8s instead of literal

2023-12-15 07:10 UTC, nilsgstrabo commented on pkg/apis/application/rolebinding.go
>  			Kind:       "RoleBinding",
Use const KindRoleBinding from defaults/k8s instead of literal

2023-12-15 07:26 UTC, nilsgstrabo commented on pkg/apis/applicationconfig/imagehubsecret.go
> +func UpdatePrivateImageHubsSecretsPassword(kubeutil *kube.Kube, appName, server, password string) error {
The function is still present. Delete it if you have moved it to radix-api

2023-12-15 07:30 UTC, nilsgstrabo commented on pkg/apis/deployment/environmentvariables_test.go
> +	if cm, err := testEnv.kubeUtil.GetConfigMap(corev1.NamespaceDefault, "radix-config"); err != nil {
Remove the `if` block. The returned configmap can be ignored as it is not used for anything here.

2023-12-15 07:35 UTC, nilsgstrabo commented on pkg/apis/dnsalias/syncer.go
> +		if admissionWebhookErrorMatcher := admissionWebhookErrorExpression.FindStringSubmatch(err.Error()); len(admissionWebhookErrorMatcher) == 5 {
I think this kind for regex matching with external error messages is unneccessary. If nginx decides to change their error message, our matching will break. Just return the original error.

2023-12-15 07:39 UTC, nilsgstrabo commented on pkg/apis/dnsalias/syncer.go
> +func buildIngress(radixDeployComponent radixv1.RadixCommonDeployComponent, radixDNSAlias *radixv1.RadixDNSAlias, dnsConfig *dnsalias.DNSConfig, oauth2Config defaults.OAuth2Config, ingressConfiguratio
Move this method to ingress.go (where it is used)

2023-12-15 07:39 UTC, nilsgstrabo commented on pkg/apis/dnsalias/syncer.go
> +func getComponentPublicPort(component radixv1.RadixCommonDeployComponent) *radixv1.ComponentPort {
Move this method to ingress.go (where it is used)

2023-12-15 07:51 UTC, nilsgstrabo requested changes
Added some new comments, and some of the previous comments are still unresolved.
Could you also update radix-common module to latest version.

2023-12-15 08:21 UTC, satr commented on pkg/apis/alert/alert_test.go
> +	}
Fixed

2023-12-15 08:22 UTC, satr commented on pkg/apis/application/rolebinding.go
>  			Kind:       "RoleBinding",
Fixed

2023-12-15 08:22 UTC, satr commented on pkg/apis/application/rolebinding.go
>  			Kind:       "RoleBinding",
Fixed

2023-12-15 08:26 UTC, satr commented on pkg/apis/deployment/environmentvariables_test.go
> +	if cm, err := testEnv.kubeUtil.GetConfigMap(corev1.NamespaceDefault, "radix-config"); err != nil {
Fixed

2023-12-15 08:28 UTC, satr commented on pkg/apis/dnsalias/syncer.go
> +func buildIngress(radixDeployComponent radixv1.RadixCommonDeployComponent, radixDNSAlias *radixv1.RadixDNSAlias, dnsConfig *dnsalias.DNSConfig, oauth2Config defaults.OAuth2Config, ingressConfiguratio
Fixed

2023-12-15 08:30 UTC, satr commented on pkg/apis/dnsalias/syncer.go
> +func getComponentPublicPort(component radixv1.RadixCommonDeployComponent) *radixv1.ComponentPort {
Fixed

2023-12-15 11:31 UTC, satr commented on pkg/apis/radix/v1/register.go
> +	Group:   "radix.equinor.com",
Fixed

2023-12-15 12:04 UTC, satr commented on pkg/apis/applicationconfig/imagehubsecret.go
> +func UpdatePrivateImageHubsSecretsPassword(kubeutil *kube.Kube, appName, server, password string) error {
Deleted. Added it as internal in radix-api

2023-12-15 13:37 UTC, satr commented on pkg/apis/dnsalias/syncer.go
> +		if admissionWebhookErrorMatcher := admissionWebhookErrorExpression.FindStringSubmatch(err.Error()); len(admissionWebhookErrorMatcher) == 5 {
Removed the method

2023-12-15 13:47 UTC, satr commented on pkg/apis/radix/v1/radixdeploytypes.go
> +	DNSAlias                []string                `json:"dnsAlias,omitempty" yaml:"dnsAlias,omitempty"`
Fixed

2023-12-15 13:47 UTC, satr commented on pkg/apis/radix/v1/radixdeploytypes.go
> +func (deployJobComponent *RadixDeployJobComponent) GetDNSAlias() []string {
Fixed

2023-12-15 13:55 UTC, satr commented on pkg/apis/radix/v1/radixdeploytypes.go
> +func (deployComponent *RadixDeployComponent) GetDNSAlias() []string {
Fixed

2023-12-15 13:55 UTC, satr commented on pkg/apis/radix/config.go
> +package radix
Removed

2023-12-18 12:37 UTC, satr commented on radix-operator/registration/controller.go
> +	}
Fixed with panic(err)

2023-12-18 12:40 UTC, satr commented on pkg/apis/test/utils.go
> +			panic(err)
Fixed

2023-12-18 12:46 UTC, satr commented on pkg/apis/test/utils.go
> +			panic(err)
Fixed

2023-12-18 12:48 UTC, satr commented on pkg/apis/utils/environment_builder_test.go
> +	assert.Equal(t, re.ObjectMeta.Finalizers[0], kube.RadixEnvironmentFinalizer)
Fixed

2023-12-18 12:54 UTC, satr commented on pkg/apis/kube/kube.go
> +	RadixDNSAliasFinalizer                           = "radix.equinor.com/dnsalias-finalizer"
Moved

2023-12-18 12:55 UTC, satr commented on radix-operator/dnsalias/controller.go
> +			logger.Errorf("failed to re-sync RadixDNSAlias %s. Error: %v", radixDNSAlias.GetName(), err)
Fixed

2023-12-18 12:56 UTC, satr commented on pkg/apis/radixvalidators/validate_ra_test.go
> +		{"dns app alias non existing component", radixvalidators.ComponentForDNSAppAliasNotDefinedError(nonExistingComponent), func(ra *v1.RadixApplication) {
It will be added in another branch

2023-12-18 12:57 UTC, satr commented on pkg/apis/test/utils.go
> +			panic(err)
Fixed

2023-12-18 12:58 UTC, satr commented on pkg/apis/radixvalidators/validate_rr.go
> +	return commonErrors.Concat(errs)
Fixed

2023-12-18 13:04 UTC, satr commented on json-schema/radixdnsalias.json
> +{
Deleted

2023-12-18 13:05 UTC, satr commented on pkg/apis/radix/v1/radixdeploytypes.go
> +	GetDNSAlias() []string
Deleted

2023-12-18 13:06 UTC, satr commented on pkg/apis/radix/register.go
> +	Version = "v1"
Fixed

2023-12-18 13:06 UTC, satr commented on pkg/apis/radix/register.go
> +	APIVersion = "radix.equinor.com/v1"
Fixed

2023-12-18 13:06 UTC, satr commented on pipeline-runner/model/pipelineInfo_test.go
> +func getDNSAliasConfig() *dnsalias.DNSConfig {
Removed

2023-12-18 13:06 UTC, satr commented on pipeline-runner/pipelines/app_test.go
> +func getDNSAliasConfig() *dnsaliasconfig.DNSConfig {
Deleted

2023-12-18 13:07 UTC, satr commented on pkg/apis/defaults/k8s/k8s.go
> +	APIVersionNetworking   = "networking.k8s.io/v1"
Fixed

2023-12-18 13:07 UTC, satr commented on pkg/apis/radix/register.go
> +const (
Fixed

2023-12-18 13:07 UTC, satr commented on pkg/apis/radix/register.go
> +	ResourceRadixDeployment = "radixdeployment"
Removed

2023-12-18 13:07 UTC, satr commented on pkg/apis/radixvalidators/validate_rr.go
> +	ErrInvalidRadixConfigFullName = fmt.Errorf("invalid file name for radixconfig. See https://www.radix.equinor.com/references/reference-radix-config/ for more information")
Fixed

2023-12-18 13:09 UTC, satr commented on pkg/apis/test/utils.go
> +func AssertError(t *testing.T, expectedError string, err error) {
Fixed

2023-12-18 13:09 UTC, satr commented on pkg/apis/kube/ingress.go
> +func (kubeutil *Kube) GetIngressesWithSelector(namespace string, labelSelectorString string) ([]*networkingv1.Ingress, error) {
Fixed

2023-12-18 13:10 UTC, satr commented on pkg/apis/dnsalias/status.go
> +		return fmt.Errorf("unable to deserealise status from annotation: %w", err)
Fixed

2023-12-18 13:11 UTC, satr commented on pkg/apis/dnsalias/status.go
> +		return fmt.Errorf("failed to sync status: %v", err)
Fixed

2023-12-18 13:12 UTC, satr commented on pkg/apis/environment/environment.go
> +func (env *Environment) handleDeletedRadixEnvironment(re *v1.RadixEnvironment) (bool, error) {
Fixed

2023-12-18 13:14 UTC, merged